[build]
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["googleapis"]

[dev]
  framework = "#static"
  targetPort = 3000
  port = 8888
  publish = "."

[build.environment]
  NODE_VERSION = "18.18.0"
