[build]
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["googleapis"]

[functions.analyze]
  timeout = 30

[dev]
  framework = "#static"
  targetPort = 3000
  port = 8888
  publish = "."

[build.environment]
  NODE_VERSION = "18.18.0"
