[build]
  functions = "netlify/functions"
  publish = "."

[dev]
  functions = "netlify/functions"
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://green-rebates-calculator.netlify.app"
    Access-Control-Allow-Methods = "OPTIONS, POST, GET"
    Access-Control-Allow-Headers = "Origin, Content-Type"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
